### ISSUE TITLE
useMemo in React SDK is not holding onto EdgeFeatureHubConfig

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub-javascript-sdk#136]
**Describe the bug**
I was running the todo-react-app, and noticed that on every poll, it is sending _two_ requests out. Adding in a bit of code here:

in FeatureHub.tsx:

````
 const fhConfig = useMemo(() => {
    console.log('creating new config in react');
    const config = new EdgeFeatureHubConfig(url, apiKey);
    config.edgeServiceProvider((repo, c) => new FeatureHubPollingClient(repo, c, pollInterval));
    return config;
  }, [apiKey, url]);
````

shows that the config is actually being initialized twice when the page loads. The docs for useMemo seem to indicate that this is possible. I'm not React savvy enough to know what to do about it...

@thedanchez do you have any ideas?

**Comment by thedanchez** [comment]
Hmm...I definitely was not expecting that. I'll have to look into it, but part of me thinks this could be due to React Strict Mode that typically runs `useEffect` hooks twice (not sure if it also applies to `useMemo` hooks so I'll have to confirm).

The expectations that the React Hook APIs have are that whatever work you do in them are *pure* or idempotent in nature. I think what we're dealing with here is something that is *stateful* in nature. All of that to say is, I'll fiddle around with getting the `useMemo` style of implementation to work and confirm whether or not my suspicions are correct. If it turns out I'm wrong, then we'll probably have to shift the implementation of how the `fhConfig` object gets made to leverage `useRef` instead.

**Comment by rvowles** [comment]
ok, i wiil leave it in your capable hands :-) I was wondering if there was something I should put into FeatureHubConfig to basically say, unless you are specifically told, if someone creates another one of you, close the second one.

But a FeatureHubConfig holds a repository and an edge connection, if you don't close it, it keeps them open, so it definitely holds state. The way they operate by default is to allow you to have as many of them as you like as you may have different use cases (e.g. a batch process that needs to use different keys), but I'm wondering if it will simply make normal browser based SDK stuff easier if you have to specifically indicate you are ok with > 1 of them.

**Comment by thedanchez** [comment]
Ah, interesting thought. Hmm, my gut instinct is telling me to keep the mental model you described intact -- but at the same time, I also like when SDKs just have a good DX (developer experience). That feeling I have comes from a place of, I think it's the React SDK's job to provide that one instance guarantee if you catch my drift.
